# OLD CONFIG
# server.port= 8080

# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.datasource.url=jdbc:h2:mem:testdb
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.datasource.initialization-mode=always
# spring.security.user.name=sa
# spring.security.user.password=


#BOOT TO USE SQL FILES IN RESOURCES DATA.SQL + SCHEMA.SQL
server.port=8080

# Database Connection
# Added DB_CLOSE_DELAY to keep the database alive in memory
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=none

spring.sql.init.mode=always

spring.jpa.defer-datasource-initialization=false

spring.security.user.name=sa
spring.security.user.password=