-- MOODS
INSERT INTO MOODS(MOOD_ID, MOOD_NAME, MOOD_SCALE) VALUES(1, 'Happy', 5);
INSERT INTO MOODS(MOOD_ID, MOOD_NAME, MOOD_SCALE) VALUES(2, 'Sad', 1);
INSERT INTO MOODS(MOOD_ID, MOOD_NAME, MOOD_SCALE) VALUES(3, 'Disgusted', -2);
INSERT INTO MOODS(MOOD_ID, MOOD_NAME, MOOD_SCALE) VALUES(4, 'Angry', -5);
INSERT INTO MOODS(MOOD_ID, MOOD_NAME, MOOD_SCALE) VALUES(5, 'Neutral', 0);

-- MOODS ENTRIES
-- INSERT INTO MOOD_ENTRIES(USER_ID, MOOD_ID, CREATED_AT) 
-- VALUES(1, 1, CURRENT_TIMESTAMP);

-- INSERT INTO MOOD_ENTRIES(USER_ID, MOOD_ID, CREATED_AT) 
-- VALUES(1, 2, DATEADD('DAY', -1, CURRENT_TIMESTAMP));

-- INSERT INTO MOOD_ENTRIES(USER_ID, MOOD_ID, CREATED_AT) 
-- VALUES(1, 5, DATEADD('DAY', -3, CURRENT_TIMESTAMP));

-- Monday
INSERT INTO MOOD_ENTRIES(USER_ID, MOOD_ID, CREATED_AT) 
VALUES(1, 1, '2026-03-23 09:00:00');

-- Tuesday
INSERT INTO MOOD_ENTRIES(USER_ID, MOOD_ID, CREATED_AT) 
VALUES(1, 5, '2026-03-24 10:30:00');

-- Wednesday
INSERT INTO MOOD_ENTRIES(USER_ID, MOOD_ID, CREATED_AT) 
VALUES(1, 2, '2026-03-25 14:00:00');

-- Thursday
INSERT INTO MOOD_ENTRIES(USER_ID, MOOD_ID, CREATED_AT) 
VALUES(1, 4, '2026-03-26 16:15:00');

-- Friday
INSERT INTO MOOD_ENTRIES(USER_ID, MOOD_ID, CREATED_AT) 
VALUES(1, 1, '2026-03-27 08:45:00');
-- Saturday

INSERT INTO MOOD_ENTRIES(USER_ID, MOOD_ID, CREATED_AT) 
VALUES(1, 2, '2026-03-27 08:45:00');

-- Sunday
INSERT INTO MOOD_ENTRIES(USER_ID, MOOD_ID, CREATED_AT) 
VALUES(1, 3, '2026-03-29 08:45:00');