CREATE TABLE moods(
    MOOD_ID INT PRIMARY KEY AUTO_INCREMENT,
    MOOD_NAME VARCHAR(50) NOT NULL,
    MOOD_SCALE INT NOT NULL
);
CREATE TABLE users(
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    AGE INT NOT NULL,
    STUDENT_STATUS BOOLEAN NOT NULL,
    PRONOUNS VARCHAR(255) NOT NULL,
    RESET_TOKEN VARCHAR(255)
);
CREATE TABLE mood_entries(
    ENTRY_ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
    MOOD_ID INT,
    CREATED_AT TIMESTAMP NOT NULL
);
